# values.yaml
replicaCount: 1

image:
  repository: "stigma137/jsonplaceholder-node-app"
  tag: "main"
  pullPolicy: IfNotPresent

service:
  name: jsonplaceholder-node-app
  type: ClusterIP
  port: 3000

# Add other environment-specific configurations as needed
