# values.yaml
replicaCount: 2

image:
  repository: "stigma137/jsonplaceholder-node-app"
  tag: "main"
  pullPolicy: Always

service:
  name: jsonplaceholder-node-app
  port: 3000
  type: LoadBalancer
  targetPort: 3000
  protocol: TCP

resources: 
  limits:
    cpu: 200m
    memory: 500Mi
  requests:
    cpu: 50m
    memory: 256Mi

serviceAccount:
  create: true
  
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: false