name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  determine-namespace:
    runs-on: ubuntu-latest

    outputs:
      namespace: ${{ steps.determine_namespace.outputs.namespace }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Determine namespace from commit message
      id: determine_namespace
      run: |
        COMMIT_MESSAGE=$(git log -1 --pretty=%B)
        if [[ $COMMIT_MESSAGE == *"[dev]"* ]]; then
          echo "namespace=dev"  >> $GITHUB_OUTPUT
        elif [[ $COMMIT_MESSAGE == *"[test]"* ]]; then
          echo "namespace=test"  >> $GITHUB_OUTPUT
        elif [[ $COMMIT_MESSAGE == *"[stage]"* ]]; then
          echo "namespace=stage"  >> $GITHUB_OUTPUT
        elif [[ $COMMIT_MESSAGE == *"[prod]"* ]]; then
          echo "namespace=prod"  >> $GITHUB_OUTPUT
        else
          echo "namespace=unknown"  >> $GITHUB_OUTPUT
        fi

    - name: Show determined namespace
      run: echo "Determined namespace is ${{ steps.determine_namespace.outputs.namespace }}"

  deploy:
    needs: determine-namespace
    runs-on: ubuntu-latest

    env:
      GKE_CLUSTER_NAME: jsonplaceholder-app-gke
      GKE_CLUSTER_ZONE: us-central1-f
      NAMESPACE: ${{ needs.determine-namespace.outputs.namespace }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud CLI
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    
    - name: Determine repository name
      id: repo_name
      run: echo "::set-output name=name::$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)"

    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: stigma137/${{ steps.repo_name.outputs.name }}


    - name: Set GKE Cluster Context
      run: gcloud container clusters get-credentials ${{ env.GKE_CLUSTER_NAME }} --zone ${{ env.GKE_CLUSTER_ZONE }}

    - name: Build and push Docker image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: 'v3.7.0'

    - name: Install Auth Plugin
      run: |
        gcloud components update
        gcloud components install kubectl
        #sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin

    - name: Deploy to GKE using Helm
      run: |
        helm upgrade --namespace ${{ env.NAMESPACE }} --install --values /charts/${{ steps.repo_name.outputs.name }}/values.yaml --wait ${{ steps.repo_name.outputs.name }} ${{ env.NAMESPACE }}/${{ steps.repo_name.outputs.name }}
